name: example
description: A new Flutter application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  extended_image: any
  extended_nested_scroll_view: any
  extended_sliver: any
  ff_annotation_route_library: ^3.0.0
  flutter:
    sdk: flutter
  http_client_helper: any
  like_button: any
  loading_more_list:
    path: ../
  pull_to_refresh_notification: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter
# dependency_overrides:
#   loading_more_list_library:
#     path: ../../loading_more_list_library
flutter:
  uses-material-design: true
  assets:
    - assets/
